name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      note:
        description: 'Manual release build (no tag required)'
        required: false

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      - name: Build
        run: |
          python -m build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nova-dist
          path: dist/*
      - name: Create GitHub Release and upload assets
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            dist/*
      - name: Publish to PyPI (optional)
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        shell: pwsh
        run: |
          if ($env:PYPI_TOKEN) {
            python -m twine upload -u __token__ -p $env:PYPI_TOKEN dist/*
          }
          else {
            echo "PYPI_TOKEN not set; skipping publish"
          }
